import { Product } from "@/components/product-card";

export const products: Product[] = [
  {
    id: 1,
    name: "Producto 1",
    slug: "producto-1",
    description:
      "Mejora tu colección de plantas con la Planta de Café. Esta planta de hojas brillantes presenta un follaje verde lustroso que prospera con luz solar indirecta brillante. Cuidar la Planta de Café es más fácil que preparar tu taza de café matutina, lo que la convierte en una adición de bajo mantenimiento y encantadora para tu espacio de vida.",
    price: 35,
    size: "M",
    image: "/hero-section.avif",
    color: "NEGRO",
  },
  {
    id: 2,
    name: "Producto 2",
    slug: "producto-2",
    description:
      "Mejora tu colección de plantas con la Planta de Café. Esta planta de hojas brillantes presenta un follaje verde lustroso que prospera con luz solar indirecta brillante. Cuidar la Planta de Café es más fácil que preparar tu taza de café matutina, lo que la convierte en una adición de bajo mantenimiento y encantadora para tu espacio de vida.",
    price: 50,
    size: "S",
    image: "/hero-section.avif",
    color: "NEGRO",
  },
  {
    id: 3,
    name: "Producto 3",
    slug: "producto-3",
    description:
      "Mejora tu colección de plantas con la Planta de Café. Esta planta de hojas brillantes presenta un follaje verde lustroso que prospera con luz solar indirecta brillante. Cuidar la Planta de Café es más fácil que preparar tu taza de café matutina, lo que la convierte en una adición de bajo mantenimiento y encantadora para tu espacio de vida.",
    price: 60,
    size: "XS",
    image: "/hero-section.avif",
    color: "NEGRO",
  },
  {
    id: 4,
    name: "Producto 4",
    slug: "producto-4",
    description:
      "Mejora tu colección de plantas con la Planta de Café. Esta planta de hojas brillantes presenta un follaje verde lustroso que prospera con luz solar indirecta brillante. Cuidar la Planta de Café es más fácil que preparar tu taza de café matutina, lo que la convierte en una adición de bajo mantenimiento y encantadora para tu espacio de vida.",
    price: 80,
    size: "M",
    image: "/hero-section.avif",
    color: "NEGRO",
  },
  {
    id: 5,
    name: "Producto 5",
    slug: "producto-5",
    description:
      "Mejora tu colección de plantas con la Planta de Café. Esta planta de hojas brillantes presenta un follaje verde lustroso que prospera con luz solar indirecta brillante. Cuidar la Planta de Café es más fácil que preparar tu taza de café matutina, lo que la convierte en una adición de bajo mantenimiento y encantadora para tu espacio de vida.",
    price: 50,
    size: "L",
    image: "/hero-section.avif",
    color: "NEGRO",
  },
  {
    id: 6,
    name: "Producto 6",
    slug: "producto-6",
    description:
      "Mejora tu colección de plantas con la Planta de Café. Esta planta de hojas brillantes presenta un follaje verde lustroso que prospera con luz solar indirecta brillante. Cuidar la Planta de Café es más fácil que preparar tu taza de café matutina, lo que la convierte en una adición de bajo mantenimiento y encantadora para tu espacio de vida.",
    price: 35,
    size: "S",
    image: "/hero-section.avif",
    color: "NEGRO",
  },
];

export const distritos = [
  "Ancón",
  "Ate",
  "Barranco",
  "Breña",
  "Carabayllo",
  "Chaclacayo",
  "Chorrillos",
  "Cieneguilla",
  "Comas",
  "El Agustino",
  "Independencia",
  "Jesús María",
  "La Molina",
  "La Victoria",
  "Lima",
  "Lince",
  "Los Olivos",
  "Lurigancho",
  "Lurín",
  "Magdalena del Mar",
  "Miraflores",
  "Pachacámac",
  "Pucusana",
  "Pueblo Libre",
  "Puente Piedra",
  "Punta Hermosa",
  "Punta Negra",
  "Rímac",
  "San Bartolo",
  "San Borja",
  "San Isidro",
  "San Juan de Lurigancho",
  "San Juan de Miraflores",
  "San Luis",
  "San Martín de Porres",
  "San Miguel",
  "Santa Anita",
  "Santa María del Mar",
  "Santa Rosa",
  "Santiago de Surco",
  "Surquillo",
  "Villa El Salvador",
  "Villa María del Triunfo"
];